## LOGGER CONFIG ##
directory: logs

stdout:
  enabled: true
  format: text
  level: info

files:
  - name: app
    enabled: true
    format: json
    level: debug

## RATE LIMIT ROUTES CONFIG ##
cleanup_interval: 5m

register:
  key_prefix: register
  window: 1m
  max_requests: 5
login:
  key_prefix: login
  window: 3m
  max_requests: 10
  # withdraw:
  #   window: 5m
  #   max_requests: 20