// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=../service/mock/user_storage_gen.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/CimaCha/gophermart-loyal-service/internal/user/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStorage is a mock of UserStorage interface.
type MockUserStorage struct {
	ctrl     *gomock.Controller
	recorder *MockUserStorageMockRecorder
	isgomock struct{}
}

// MockUserStorageMockRecorder is the mock recorder for MockUserStorage.
type MockUserStorageMockRecorder struct {
	mock *MockUserStorage
}

// NewMockUserStorage creates a new mock instance.
func NewMockUserStorage(ctrl *gomock.Controller) *MockUserStorage {
	mock := &MockUserStorage{ctrl: ctrl}
	mock.recorder = &MockUserStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStorage) EXPECT() *MockUserStorageMockRecorder {
	return m.recorder
}

// FindUserInfo mocks base method.
func (m *MockUserStorage) FindUserInfo(ctx context.Context, userLogin string) (model.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserInfo", ctx, userLogin)
	ret0, _ := ret[0].(model.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserInfo indicates an expected call of FindUserInfo.
func (mr *MockUserStorageMockRecorder) FindUserInfo(ctx, userLogin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserInfo", reflect.TypeOf((*MockUserStorage)(nil).FindUserInfo), ctx, userLogin)
}

// SaveUserInfo mocks base method.
func (m *MockUserStorage) SaveUserInfo(ctx context.Context, userInfo model.UserInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserInfo", ctx, userInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUserInfo indicates an expected call of SaveUserInfo.
func (mr *MockUserStorageMockRecorder) SaveUserInfo(ctx, userInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserInfo", reflect.TypeOf((*MockUserStorage)(nil).SaveUserInfo), ctx, userInfo)
}
