// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/CimaCha/gophermart-loyal-service/internal/gophermart/balance/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBalanceRepository creates a new instance of MockBalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBalanceRepository is an autogenerated mock type for the BalanceRepository type
type MockBalanceRepository struct {
	mock.Mock
}

type MockBalanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceRepository) EXPECT() *MockBalanceRepository_Expecter {
	return &MockBalanceRepository_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function for the type MockBalanceRepository
func (_mock *MockBalanceRepository) GetBalance(ctx context.Context, userID uuid.UUID) (model.Balance, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 model.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Balance, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Balance); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.Balance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceRepository_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockBalanceRepository_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockBalanceRepository_Expecter) GetBalance(ctx any, userID any) *MockBalanceRepository_GetBalance_Call {
	return &MockBalanceRepository_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *MockBalanceRepository_GetBalance_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockBalanceRepository_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceRepository_GetBalance_Call) Return(balance model.Balance, err error) *MockBalanceRepository_GetBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockBalanceRepository_GetBalance_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (model.Balance, error)) *MockBalanceRepository_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}
