// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenBuilder creates a new instance of MockTokenBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenBuilder {
	mock := &MockTokenBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenBuilder is an autogenerated mock type for the TokenBuilder type
type MockTokenBuilder struct {
	mock.Mock
}

type MockTokenBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenBuilder) EXPECT() *MockTokenBuilder_Expecter {
	return &MockTokenBuilder_Expecter{mock: &_m.Mock}
}

// BuildJWTString provides a mock function for the type MockTokenBuilder
func (_mock *MockTokenBuilder) BuildJWTString(uUID uuid.UUID) (string, error) {
	ret := _mock.Called(uUID)

	if len(ret) == 0 {
		panic("no return value specified for BuildJWTString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (string, error)); ok {
		return returnFunc(uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) string); ok {
		r0 = returnFunc(uUID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenBuilder_BuildJWTString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildJWTString'
type MockTokenBuilder_BuildJWTString_Call struct {
	*mock.Call
}

// BuildJWTString is a helper method to define mock.On call
//   - uUID uuid.UUID
func (_e *MockTokenBuilder_Expecter) BuildJWTString(uUID any) *MockTokenBuilder_BuildJWTString_Call {
	return &MockTokenBuilder_BuildJWTString_Call{Call: _e.mock.On("BuildJWTString", uUID)}
}

func (_c *MockTokenBuilder_BuildJWTString_Call) Run(run func(uUID uuid.UUID)) *MockTokenBuilder_BuildJWTString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenBuilder_BuildJWTString_Call) Return(s string, err error) *MockTokenBuilder_BuildJWTString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenBuilder_BuildJWTString_Call) RunAndReturn(run func(uUID uuid.UUID) (string, error)) *MockTokenBuilder_BuildJWTString_Call {
	_c.Call.Return(run)
	return _c
}
