// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"context"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactor creates a new instance of MockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactor {
	mock := &MockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactor is an autogenerated mock type for the Transactor type
type MockTransactor struct {
	mock.Mock
}

type MockTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactor) EXPECT() *MockTransactor_Expecter {
	return &MockTransactor_Expecter{mock: &_m.Mock}
}

// BeginFunc provides a mock function for the type MockTransactor
func (_mock *MockTransactor) BeginFunc(ctx context.Context, fn func(pgx.Tx) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for BeginFunc")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(pgx.Tx) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactor_BeginFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginFunc'
type MockTransactor_BeginFunc_Call struct {
	*mock.Call
}

// BeginFunc is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(pgx.Tx) error
func (_e *MockTransactor_Expecter) BeginFunc(ctx any, fn any) *MockTransactor_BeginFunc_Call {
	return &MockTransactor_BeginFunc_Call{Call: _e.mock.On("BeginFunc", ctx, fn)}
}

func (_c *MockTransactor_BeginFunc_Call) Run(run func(ctx context.Context, fn func(pgx.Tx) error)) *MockTransactor_BeginFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(pgx.Tx) error
		if args[1] != nil {
			arg1 = args[1].(func(pgx.Tx) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactor_BeginFunc_Call) Return(err error) *MockTransactor_BeginFunc_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactor_BeginFunc_Call) RunAndReturn(run func(ctx context.Context, fn func(pgx.Tx) error) error) *MockTransactor_BeginFunc_Call {
	_c.Call.Return(run)
	return _c
}
