// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBalanceAccruer creates a new instance of MockBalanceAccruer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceAccruer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceAccruer {
	mock := &MockBalanceAccruer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBalanceAccruer is an autogenerated mock type for the BalanceAccruer type
type MockBalanceAccruer struct {
	mock.Mock
}

type MockBalanceAccruer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceAccruer) EXPECT() *MockBalanceAccruer_Expecter {
	return &MockBalanceAccruer_Expecter{mock: &_m.Mock}
}

// AccrueTx provides a mock function for the type MockBalanceAccruer
func (_mock *MockBalanceAccruer) AccrueTx(ctx context.Context, tx pgx.Tx, userID uuid.UUID, orderNum string, sum decimal.Decimal) error {
	ret := _mock.Called(ctx, tx, userID, orderNum, sum)

	if len(ret) == 0 {
		panic("no return value specified for AccrueTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID, string, decimal.Decimal) error); ok {
		r0 = returnFunc(ctx, tx, userID, orderNum, sum)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBalanceAccruer_AccrueTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccrueTx'
type MockBalanceAccruer_AccrueTx_Call struct {
	*mock.Call
}

// AccrueTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - userID uuid.UUID
//   - orderNum string
//   - sum decimal.Decimal
func (_e *MockBalanceAccruer_Expecter) AccrueTx(ctx any, tx any, userID any, orderNum any, sum any) *MockBalanceAccruer_AccrueTx_Call {
	return &MockBalanceAccruer_AccrueTx_Call{Call: _e.mock.On("AccrueTx", ctx, tx, userID, orderNum, sum)}
}

func (_c *MockBalanceAccruer_AccrueTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, userID uuid.UUID, orderNum string, sum decimal.Decimal)) *MockBalanceAccruer_AccrueTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 decimal.Decimal
		if args[4] != nil {
			arg4 = args[4].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBalanceAccruer_AccrueTx_Call) Return(err error) *MockBalanceAccruer_AccrueTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBalanceAccruer_AccrueTx_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, userID uuid.UUID, orderNum string, sum decimal.Decimal) error) *MockBalanceAccruer_AccrueTx_Call {
	_c.Call.Return(run)
	return _c
}
